name: test-windows
on: 
# push, pullrequest時にci実行
    push:
        paths-ignore:
          - '.gitignore'
          - 'LICENSE'
          - '**.md'
    pull_request:
        paths-ignore:
          - '.gitignore'
          - 'LICENSE'
          - '**.md'
jobs:
  build:
    name: MSBuild
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Install Server-Media-Foundation
        shell: powershell
        run: |
          msbuild -version

      - name: Install related packages
        shell: powershell
        run: |
          winget --version
          winget install Git.Git 
          git --version
          winget install python.python
          python --version
          pip install pyqt5
          pip install numpy

      - name: Do tetris
        shell: powershell
        run: |
          cd ~
          mkdir work
          cd work
          git clone https://github.com/seigot/tetris
          cd tetris
          python start.py
