name: Check URLs

on:
  push:
    paths: 
      - 'README.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check URLs
        uses: paramt/url-checker@master
        with:
          files: "README.md"
